### ISSUE TITLE
[Feature request] Update parameter value of existing node instead of recreating the graph

### ISSUE THREAD

**Issue by EtiennePhillipsBeckhoff** [Mobject-Dev-Team/mobject-graph#8]
Currently, when using nodes that have a state (like a PID controller that contains the accumulated integral value), changing any node's parameter value recreates the whole graph from scratch, causing all the state information to be lost.

Changing this to an update would mean that on-the-fly changes become possible with minimal disruption.

**Comment by benhar-dev** [comment]
Yep, totally possible to do.  I'll add this to the todo list.  I feel this should be a quick addition so I'll work on this next.
